### ISSUE TITLE
Please list plugin types

### ISSUE THREAD

**Issue by spamatica** [ardura/Actuate#36]
Found your synth, looks nice!

I was just gonna ask you to kindly list somewhere what kind of plugins it implements.
Unless I'm blind and it's already there...

**Comment by ardura** [comment]
Hello! That's a great idea, I'll add that to the readme once I'm back at my PC. For reference I package the VST3 and CLAP versions for windows 10+, MacOS12, and Linux (compiled on Ubuntu). 

Is that what you mean?

**Comment by spamatica** [comment]
Indeed that is what I'm after. I didn't find this info, in the end I found it by looking in one of the released binaries.

I'm a long time Linux audio user and the plugin support varies _a_lot_ between different hosts, so it is very useful information to at least know what the plugin supports :)

**Comment by spamatica** [comment]
Decided to reopen it so you can close it when you actually added the text.

I propose adding a paragraph under compatibility.

**Comment by ardura** [comment]
Added to Readme, thanks for the suggestion!
![image](https://github.com/ardura/Actuate/assets/31751444/ba23f753-1765-462b-ab7b-839fe1292046)
