### ISSUE TITLE
StudioRack integration

### ISSUE THREAD

**Issue by RustoMCSpit** [ardura/Actuate#39]
It's an open-source plugin manager called StudioRack:
https://github.com/studiorack

The aim of the project is to provide a free open-source way to manage plugin dependencies and their versions. It would involve the following steps:

    Publish a Github release containing the plugin source along with metadata plugins.json
    Tag your Github repository with studiorack-plugin so it can be discovered
    Wait for the studiorack-registry to index your plugin (every 24 hours)
    Check the registry feed for your plugin to appear

**Comment by ardura** [comment]
Wow that seems really cool! I'll see if I can add that in the upcoming release I'm working on

**Comment by RustoMCSpit** [comment]
> Wow that seems really cool! I'll see if I can add that in the upcoming release I'm working on

any issues you have please contact dev on discord or make issue requests in the github repo

**Comment by ardura** [comment]
Studio rack integrated successfully

**Comment by RustoMCSpit** [comment]
> Studio rack integrated successfully

do you only plan to do this for this plugin or will you do it for all of them?
