### ISSUE TITLE
Filter Envelope sustain level maxes out at set cutoff level - envelope release end point always above set sustain level

### ISSUE THREAD

**Issue by Dtard** [ardura/Actuate#45]
Recording to demonstrate below.

The filter envelope sustain stage is always below the set cutoff (max sustain = set cutoff), which causes the filter to open during the release stage.
Because the envelope attack stage ends at (set cutoff + env mod), this also creates the issue that the sustain point (max = cutoff) will always be lower than cutoff + env and at max sustain the filter will still close during the decay stage.

One other thing here is that the filter and filter envelope seem to be monophonic regardless of max voices. Not Necessarily a bug but it would be beneficial to have polyphonic filter. The issue that this causes is that when releasing a note while another note is held, the release stage takes priority, which causes the filter on the note still being held to be sustained at the set cutoff point (which is above the set sustain point as detailed above). 

also wanted to say it's possible I missed some mode switch and am incorrect.

Issue demo:
[https://soundcloud.com/ovrmnd/actuate-envelope-cutoff-end/s-0ghFtfXUQW0?si=c14ab2ed972f49b99a25a8647638fa08&utm_source=clipboard&utm_medium=text&utm_campaign=social_sharing](url)

**Comment by ardura** [comment]
Hey @Dtard thanks for checking out Actuate! It's not really a bug but it's definitely undesired behavior on the release env with the filter. I was considering adding a toggle that is on by default to ignore the release for the filter to make it behave more similar to other synths since I have also considered there *could be* some people that like that behavior already (even if neither you or I do). I also want to look at a few synths to see how their filter releases work!

As for the monophonic filter I definitely agree. It might be doable now that I know a lot more having worked on Actuate for a while, so I'll start looking at both of those ideas in the next big update 👍

**Comment by Dtard** [comment]
Definitely - I really like the direction the synth is going so far and appreciate the work you're putting in on it! 
> I was considering adding a toggle that is on by default to ignore the release for the filter to make it behave more similar to other synths since I have also considered there _could be_ some people that like that behavior already (even if neither you or I do). 

I think the most interesting way to develop this would be possibly instead of a toggle, an additional slider to select end point. Not sure if this exist so let's just say it would be an ADSRE envelope. You can have center as 50% cutoff or have 50% be the set cutoff point, although this could cause weird variable scaling depending on cutoff point.

> I also want to look at a few synths to see how their filter releases work!

99% of synths I have seen use (cutoff + env) as the point reached at end of attack (cutoff + sustain) as the sustain point, and just the base cutoff as the end point for release. The other 1% are usually inverse so the max value reached is the set cutoff - start point is (cutoff - env), attack ends at cutoff, sustain is like (cutoff - env + sustain), releasing back to (cutoff - env). Exciting stuff I know. 

That being said I do really enjoy the more unique things you're doing here with the interesting filter types - I'd say to get as unique and experimental as you'd like. The wackiest envelopes I've seen have been the 8-segment Casio CZ envelopes, but that style of envelope seems to have been obsoleted by editable graph-based multi-segment envelope generators.

**Comment by ardura** [comment]
Hey @Dtard ! So I have reworked the envelopes for the filters to line up better and here is the current behavior:
1. Attack starts at (filter cutoff) and moves toward (filter cutoff + peak)
2. Decay starts wherever attack is at that time and moves towards (filter cutoff + peak)*sustain amount
3. Sustain state is just the last position of the decay (filter cutoff + peak)*sustain amount
4. Release is from wherever state/position we were in before, moving towards (filter cutoff)

I have had some requests for multi segment envelopes but I think I would rather do the polyphonic filter first, besides I'm more partial to automating the movements in my DAW than in the synth itself most of the time, but that's just my use case!

Update dropping soon!
