### ISSUE TITLE
Crash in Reaper when clicking on a parameter description

### ISSUE THREAD

**Issue by koalastudio72** [ardura/Actuate#52]
Hi ardura,
I played a little bit with your synth. Sound really good, thanks a lot for sharing.
I think, I found a little bug.
In FX-Tab, when I click on the description of the parameter, then my DAW crashes immediately.
For example: 
In the compressor-section I click on the description: Amount:0.30 -> Crash
The parameter values with the sliders right from the description can be changed without crashes.
So, this is not a big problem, but perhaps something you may correct in some time.
Thanks in advance.

My configuration:
WIN 10 (22H2)
Cockos Reaper 7.28

**Comment by ardura** [comment]
Hi @koalastudio72, that's a good catch thanks. Seems like it is crashing same for me when I tried on FL! So I'll definitely need to fix that thank you. I'm working on the update for next year so I'll see if I can add that in 👍

**Comment by koalastudio72** [comment]
Now it works for me. 👍
Thank you.
